### ISSUE TITLE
Springer router issue!

### ISSUE THREAD

**Issue by BensenHsu** [DIYgod/RSSHub#13469] opened 2023-10-05 20:24 UTC
### Routes

```routes
/springer/journal/:journal
```

### Full routes

```fullroutes
https://rsshub.app/springer/journal/40820
https://rsshub.app/springer/journal/41114
```

### Related documentation

https://docs.rsshub.app/routes/journal#springer-journal

### What is expected?

The RSS urls should return the XML content of `Nano-Micro Letters` and `Living Reviews in Relativity`, respectively, but instead they reported the error.

### What is actually happening?

Looks like something went wrong
Route requested: /journal/40820
Error message: Missing `url` property: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /journal/40820
Node version: v18.18.0
Git Hash: 383fb9f
        
If you believe this is an error caused by RSSHub, please report on github
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 汇报
        
For online documentation and support please refer to docs.rsshub.app.

在线文档与支持，请访问 docs.rsshub.app。

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
N.A.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2023-10-05 20:46
Duplicate of #13468

**Closed by TonyRL** 2023-10-05 20:46 UTC
Labels: RSS bug, route: v2, Count: 1/1
