### ISSUE TITLE
懂球帝球队新闻rss失效

### ISSUE THREAD

**Issue by JamYiz** [DIYgod/RSSHub#8560] opened 2021-11-19 10:05 UTC
#### 路由地址（不包含参数）
/dongqiudi/team_news/:team
```routes
```

#### 完整路由地址，包含所有必选与可选参数
/dongqiudi/result/50001755
```fullroutes:

```

#### 相关文档地址

- https://docs.rsshub.app/new-media.html#dong-qiu-di

#### 实际发生了什么
Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /dongqiudi/team_news/50001755
Node version: v14.18.1
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by TonyRL** [comment] 2021-11-19 11:46
Duplicate of https://github.com/DIYgod/RSSHub/issues/8468

Which may be fixed by
- [ ] https://github.com/DIYgod/RSSHub/pull/8526

**Closed** 2022-02-01 19:44 UTC
