### ISSUE TITLE
1tamilmv

### ISSUE THREAD

**Issue by akashmuraliNEW** [DIYgod/RSSHub#14240] opened 2024-01-14 16:32 UTC
### Category

Uncategorized

### Website URL

https://www.1tamilmv.world/

### Website description

Torrent site

### What content should be included?

Title 
Magnetic links

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment] 2024-01-15 18:25
Duplicate of #12651

**Closed by TonyRL** 2024-01-15 18:25 UTC
Labels: RSS proposal
