### ISSUE TITLE
🔴「拷贝漫画」RSS 失效

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#11404] opened 2022-12-07 17:19 UTC
### 路由地址

```routes
/copymanga/comic/:id/:chapterCnt?
```

### 完整路由地址

```fullroutes
/copymanga/comic/xiangyaochengweiyingzhishilizhe/0
```

### 相关文档

https://docs.rsshub.app/anime.html#kao-bei-man-hua-man-hua-geng-xin

## 「官方演示」和「自建」均出现报错

https://rsshub.app/copymanga/comic/xiangyaochengweiyingzhishilizhe/0

## Looks like something went wrong

Route requested: /copymanga/comic/xiangyaochengweiyingzhishilizhe/0
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
Helpful Information to provide when opening issue:
Path: /copymanga/comic/xiangyaochengweiyingzhishilizhe/0
Node version: v16.18.1

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Node version: v16.18.1

### 额外信息

```shell
Route requested: /copymanga/comic/xiangyaochengweiyingzhishilizhe/0
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /copymanga/comic/xiangyaochengweiyingzhishilizhe/0
Node version: v16.18.1
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment] 2022-12-07 17:45
Duplicate of #11215

**Closed by TonyRL** 2022-12-07 17:45 UTC
Labels: RSS bug, Count: 0/1, Bug Ping: Pinged, Route: v1
