### ISSUE TITLE
vercel部署失败，Error: ENOENT: no such file or directory, open '/vercel/path0/assets/build/radar-rules.json'

### ISSUE THREAD

**Issue by louyongjiu** [DIYgod/RSSHub#18005] opened 2024-12-30 06:08 UTC
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/deploy/

### 预期是什么？

vercel部署成功

### 实际发生了什么？

[14:02:53.537] Running "pnpm run build"
[14:02:54.045] 
[14:02:54.046] > rsshub@1.0.0 build /vercel/path0
[14:02:54.046] > tsx scripts/workflow/build-routes.ts
[14:02:54.046] 
[14:03:17.134] node:fs:2344
[14:03:17.135]     return binding.writeFileUtf8(
[14:03:17.135]                    ^
[14:03:17.135] 
[14:03:17.135] Error: ENOENT: no such file or directory, open '/vercel/path0/assets/build/radar-rules.json'
[14:03:17.135]     at Object.writeFileSync (node:fs:2344:20)
[14:03:17.135]     at <anonymous> (/vercel/path0/scripts/workflow/build-routes.ts:70:4) {
[14:03:17.135]   errno: -2,
[14:03:17.135]   code: 'ENOENT',
[14:03:17.135]   syscall: 'open',
[14:03:17.135]   path: '/vercel/path0/assets/build/radar-rules.json'
[14:03:17.135] }
[14:03:17.135] 
[14:03:17.136] Node.js v22.12.0
[14:03:17.183]  ELIFECYCLE  Command failed with exit code 1.
[14:03:17.199] Error: Command "pnpm run build" exited with 1

### 部署

自建

### 部署相关信息

vercel node22

### 额外信息

```shell
[14:02:53.537] Running "pnpm run build"
[14:02:54.045] 
[14:02:54.046] > rsshub@1.0.0 build /vercel/path0
[14:02:54.046] > tsx scripts/workflow/build-routes.ts
[14:02:54.046] 
[14:03:17.134] node:fs:2344
[14:03:17.135]     return binding.writeFileUtf8(
[14:03:17.135]                    ^
[14:03:17.135] 
[14:03:17.135] Error: ENOENT: no such file or directory, open '/vercel/path0/assets/build/radar-rules.json'
[14:03:17.135]     at Object.writeFileSync (node:fs:2344:20)
[14:03:17.135]     at <anonymous> (/vercel/path0/scripts/workflow/build-routes.ts:70:4) {
[14:03:17.135]   errno: -2,
[14:03:17.135]   code: 'ENOENT',
[14:03:17.135]   syscall: 'open',
[14:03:17.135]   path: '/vercel/path0/assets/build/radar-rules.json'
[14:03:17.135] }
[14:03:17.135] 
[14:03:17.136] Node.js v22.12.0
[14:03:17.183]  ELIFECYCLE  Command failed with exit code 1.
[14:03:17.199] Error: Command "pnpm run build" exited with 1
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment] 2024-12-30 06:10
Duplicate of #14622

**Closed by TonyRL** 2024-12-30 06:10 UTC
Labels: RSS bug
