### ISSUE TITLE
🔴 Bangumi 放送列表 RSS 报错

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#9878] opened 2022-06-02 16:00 UTC
### 路由地址

```routes
/bangumi/calendar/today
```

### 完整路由地址

```fullroutes
https://rsshub.app/bangumi/calendar/today
```

### 相关文档

https://docs.rsshub.app/anime.html#bangumi-fang-song-lie-biao

## Looks like something went wrong

- Route requested: /bangumi/calendar/today

- Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

- Helpful Information to provide when opening issue:

- Path: /bangumi/calendar/today

- Node version: v16.3.0

- Git Hash: 548395b

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
「官方示例」和「自建」均出现报错
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment] 2022-06-02 16:04
Duplicate of #8451

**Closed by TonyRL** 2022-06-02 16:04 UTC
Labels: RSS bug, Count: 0/1, Bug Ping: Pinged, Route: v1

**Comment by xiaobailoves** [comment] 2022-07-22 03:22
我也有这个问题
