### ISSUE TITLE
GitHub trending RSS 失效

### ISSUE THREAD

**Issue by fz6m** [DIYgod/RSSHub#16853] opened 2024-09-21 21:01 UTC
### Routes

https://rsshub.app/github/trending/daily/javascript

只能获取到 9 月 18 日的缓存了，这之后就是挂的状态。

访问其他任何 RSSHUB instance ，这个订阅都是挂的状态：`Looks like something went wrong
` 。

### Full routes

```fullroutes
_
```

### Related documentation

https://docs.rsshub.app/routes/popular#trending

### What is expected?

_

### What is actually happening?

_

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
_
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2024-09-22 00:43
Duplicate of #16849

**Closed** 2024-09-22 00:43 UTC
Labels: RSS bug, Bug Ping: Parsing Failed
