### ISSUE TITLE
Self-hosted Science Magazine cannot use

### ISSUE THREAD

**Issue by fyihang** [DIYgod/RSSHub#11080] opened 2022-10-13 09:24 UTC
### Routes

```routes
/science/current/:journal?
```

### Full routes

```fullroutes
/science/current/science
/science/current/sciadv
/science/current/sciimmunol
/science/current/scirobotics
/science/current/signaling
/science/current/stm
```

### Related documentation

https://docs.rsshub.app/en/journal.html#science-magazine

### What is expected?

get an xml

### What is actually happening?

unable to get xml

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: CentOS 7.6, Node: v16.17.1, Docker: 20.10.18

### Additional info

```shell
Error message: Navigation timeout of 30000 ms exceeded
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2022-10-13 10:57
Duplicate of #11069

**Comment by TonyRL** [comment] 2022-10-13 10:58
Duplicate of #11069

**Closed** 2022-10-13 10:57 UTC
Labels: RSS bug, Bug Ping: Pinged, Count: 1/1, Route: v2
