### ISSUE TITLE
为经济学人Espresso页面建一个RSS源

### ISSUE THREAD

**Issue by ispmz** [DIYgod/RSSHub#8515] opened 2021-11-11 07:39 UTC
### Website URL
https://www.economist.com/espresso
### Website description
The Economist Daily Briefing - Your 5-minute break to catch up on today’s essential news.
### What content should be included?

- 

 ![image](https://user-images.githubusercontent.com/68932348/141256364-76ca810c-164a-490a-a351-fd6cb18712c3.png)

- 

![image](https://user-images.githubusercontent.com/68932348/141256543-e75143f6-7616-4a3e-84dd-3d9d2e1bac6e.png)

-

 ![image](https://user-images.githubusercontent.com/68932348/141256652-57118323-7549-45a2-a21e-b045c96f34bc.png)

-

 ![image](https://user-images.githubusercontent.com/68932348/141256733-ed9abd63-01fd-469b-806f-9e1f85d41e40.png)

**Comment by TonyRL** [comment] 2021-11-11 10:04
Duplicate of https://github.com/DIYgod/RSSHub/issues/7323

**Closed** 2022-01-26 12:30 UTC
