### ISSUE TITLE
Instagram route not working

### ISSUE THREAD

**Issue by e-gor** [DIYgod/RSSHub#17826] opened 2024-12-08 15:12 UTC
### Routes

```routes
/instagram/:category/:key
```

### Full routes

```fullroutes
/instagram/user/stefaniejoosten
```

### Related documentation

https://docs.rsshub.app/routes/social-media#instagram

### What is expected?

The RSS of the user's posts

### What is actually happening?

In the rsshub.app instance, it returns a "401 Unauthorized" error, which would be logical if the instance does not have an Instagram account configured with the username and password.

But I have installed RSSHub on my own server, I have put the variables IG_USERNAME and IG_PASSWORD in the conf file, and now the error it returns is "IgLoginBadPasswordError: POST /api/v1/accounts/login/ - 400 Bad Request; We can send you an email to help you get back into your account.".

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Linux; Node: v22.12.0

### Additional info

```shell
IgLoginBadPasswordError: POST /api/v1/accounts/login/ - 400 Bad Request; We can send you an email to help you get back into your account.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2024-12-08 16:06
Duplicate of #14394

**Comment by TonyRL** [comment] 2024-12-08 16:06
> Login the same account on Instagram App/Web and make sure your account is not limited.

_Originally posted by TonyRL in https://github.com/DIYgod/RSSHub/issues/14394#issuecomment-1932521623_

**Closed** 2024-12-10 01:28 UTC
Labels: RSS bug
