### ISSUE TITLE
【ERROR】抖音博主 路由失效

### ISSUE THREAD

**Issue by 9k001** [DIYgod/RSSHub#16209] opened 2024-07-19 11:04 UTC
### Routes

```routes
/douyin/user/:uid/:routeParams?
```

### Full routes

```fullroutes
/douyin/user/:uid/:routeParams?
```

### Related documentation

https://docs.rsshub.app/routes/social-media#%E5%8D%9A%E4%B8%BB

### What is expected?

获取当前博主段视频

### What is actually happening?

Helpful Information

Error Message:
TypeError: Cannot read properties of undefined (reading 'user')

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Helpful Information

Error Message:
Error: Empty html. The request may be filtered by WAF.

Route: /douyin/user/:uid/:routeParams?

Full Route: /douyin/user/MS4wLjABAAAARcAHmmF9mAG3JEixq_CdP72APhBlGlLVbN-1eBcPqao

Node Version: v22.4.1

Git Hash: a1a3ab42

Git Date: Thu, 18 Jul 2024 11:03:22 GMT
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2024-07-19 11:57
Duplicate of #12029

**Closed by TonyRL** 2024-07-19 11:57 UTC
Labels: RSS bug
