### ISSUE TITLE
RSS中推特的专用参数和通用参数可以一起使用么？可以的话怎么用？

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#9988] opened 2022-06-19 06:16 UTC
### 这是一个什么样的功能？

非新功能。

### 这个功能可以解决什么问题？

我尝试这两个参数一起用，发现要不就不工作要不就不显示。
例如：
https://rsshub.bgme.me/twitter/user/kaede_idoit?filterout_title=RT&filter_description=img/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showQuotedAuthorAvatarInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150

### 额外描述

可以的话麻烦讲解一下怎么用，先谢谢作者。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by Rongronggg9** [comment] 2022-06-19 12:17
Duplicate of #9939

But I request @TonyRL to close and lock that issue instead of this due to the below reasons:

The author of #9939 asked some questions and then blocked me, showing uncooperative behavior and the potential to not respect contributors but make them embarrassed. I had to request closing and locking this issue since the author has shown the potential to not accept others' opinions and answers but to change the issue to the author's personal stage.

As a result, I have to reply to the author of #9939 here:

<details>

> But why `/twitter/user/durov?key=123&count=5` is not valid?

Due to the route cache mechanism, the query is NOT a part of the cache key while the path is. As a result, routes cannot rely on queries to read per route options, otherwise, they would not take effect until the route cache expired.
Some collaborators (not including me, I don't have that honor to be a collaborator) may be planning on unifying the two, but IDK if it would end up like other previous plans of RSSHub. IMO it is the current solution the one that fits my intuition.

> The documentation should be improved how to combine access key with route options.

PR is welcomed. 

> 阴阳怪气？

It's just a book recommendation to tell that all things about computers are just kind of out of intuition until you really have a deep dive. Of course, that's your freedom to take such a thought into your mind.

> 这书你读完了吗？

Otherwise how did I know it is a nice book?

</details>

**Comment by Rongronggg9** [comment] 2022-06-19 12:19
Valid usage:
```
https://rsshub.bgme.me/twitter/user/kaede_idoit/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showQuotedAuthorAvatarInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150?filterout_title=RT&filter_description=img
```

**Comment by TonyRL** [comment] 2022-06-19 19:39
Duplicate of #9939

**Closed by TonyRL** 2022-06-19 19:39 UTC
Labels: RSS enhancement
