### ISSUE TITLE
AppStore IAP RSS bug

### ISSUE THREAD

**Issue by iedkujqmbly** [DIYgod/RSSHub#3509] opened 2019-11-30 03:28 UTC
### 路由地址
https://rsshub.app/appstore/iap/cn/id1472328263

### 预期是什么？
返回 https://apps.apple.com/cn/app/id1472328263 的 IAP 价格变化

### 实际发生了什么？
报错。

**Comment by DIYgod** [comment] 2019-12-02 07:32
Duplicate of #3490

**Comment by iedkujqmbly** [comment] 2019-12-09 06:28
@DIYgod 感谢重新打开，请检查一下此 issue 多谢！

**Comment by iedkujqmbly** [comment] 2019-12-09 06:29
https://rsshub.app/appstore/iap/cn/id1472328263
报告如下错误：

Looks like something went wrong
TypeError: Cannot read property 'url' of undefined
at /data/wwwroot/rsshub.app/lib/routes/apple/appstore/in-app-purchase.js:47:103
at Array.map ()
at module.exports (/data/wwwroot/rsshub.app/lib/routes/apple/appstore/in-app-purchase.js:42:20)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:203:9)
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Closed** 2019-12-12 03:45 UTC
Labels: bug
