### ISSUE TITLE
[ERROR]https://rsshub.app/smzdm/ranking/dianshang/31/3

### ISSUE THREAD

**Issue by ccinoo** [DIYgod/RSSHub#3338] opened 2019-10-27 11:10 UTC
### 路由地址
https://rsshub.app/smzdm/ranking/dianshang/31/3
### 预期是什么？
正常 rss源返回
### 实际发生了什么？
返回报错
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by DIYgod** [comment] 2019-10-28 06:28
Duplicate of #3330

**Closed by DIYgod** 2019-10-28 06:28 UTC
