### ISSUE TITLE
【源报错】纽约时报源报错

### ISSUE THREAD

**Issue by ccinoo** [DIYgod/RSSHub#8717] opened 2021-12-12 13:02 UTC
### 路由地址

/nytimes/dual

### 完整路由地址

https://rsshub.app/nytimes/dual

### 相关文档

https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao

### 预期是什么？

正常返回rss信息

### 实际发生了什么？

Looks like something went wrong
Route requested: /nytimes/dual
Error message: Failed to launch the browser process!
/root/RSSHub/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Helpful Information to provide when opening issue: 
Path: /nytimes/dual
Node version: v16.3.0

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /nytimes/dual
Error message: Failed to launch the browser process!
/root/RSSHub/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Helpful Information to provide when opening issue: 
Path: /nytimes/dual
Node version: v16.3.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment] 2021-12-12 14:14
Possible duplicate of https://github.com/DIYgod/RSSHub/issues/7591, https://github.com/DIYgod/RSSHub/issues/7755, https://github.com/DIYgod/RSSHub/issues/8407 and https://github.com/DIYgod/RSSHub/issues/8513

Puppeteer is not available on demo instance.

> You are encouraged to [host your own RSSHub instance](https://docs.rsshub.app/en/install/) to get a better usability.
>
> [FAQs | RSSHub](https://docs.rsshub.app/en/faq.html)


> 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

This is a duplicated issue that has been reported several times.

**Comment by TonyRL** [comment] 2022-03-02 13:51
Routes using puppeteer is working again on demo instance.

**Closed by TonyRL** 2022-03-02 13:51 UTC
Labels: RSS bug, duplicate
