### ISSUE TITLE
X (Twitter): Return full text of longer tweets for user timeline

### ISSUE THREAD

**Issue by nwly** [DIYgod/RSSHub#16844] opened 2024-09-21 07:03 UTC
### What feature is it?

Extract full tweet content even for longer tweets for route `/twitter/user/:id/:routeParams?`.  Currently, this only returns the beginning portion before the "Show More" link for longer tweets.  E.g., 

![image](https://github.com/user-attachments/assets/b120c41d-a6dc-45bf-930a-bcc156ac8a82)

results in:

![image](https://github.com/user-attachments/assets/7807daeb-d341-4e60-ac71-24cc16ac6590)

But the full tweet is actually:

![image](https://github.com/user-attachments/assets/fb4abe6b-1e0e-4200-8b11-6834397bf172)

### What problem does this feature solve?

Having this feature prevents the RSS user to have to open the tweet link to see the full text, meaning that they don't need to go back and forth between whatever RSS reader app they are using and the X/Twitter webapp.

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment] 2024-09-21 07:47
Duplicate of #12360

**Closed by TonyRL** 2024-09-21 07:47 UTC
Labels: RSS enhancement
