### ISSUE TITLE
heroku 一键部署失败

### ISSUE THREAD

**Issue by g19830805** [DIYgod/RSSHub#16923] opened 2024-09-25 22:52 UTC
### 路由地址

```routes
/twitter/keyword/:keyword/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/keyword/:keyword/:routeParams?
```

### 相关文档

https://heroku.com/deploy?template=https%3A%2F%2Fgithub.com%2FDIYgod%2FRSSHub

### 预期是什么？

heroku一键部署成功

### 实际发生了什么？

![2024-09-26_063815](https://github.com/user-attachments/assets/3d4f3744-04f0-4992-ac67-7517b0e550fa)

App creation failed. 
Please ensure you have valid values in the above form fields.

Configure environment
Build app Hide build log

There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

### 部署

自建

### 额外信息

```shell
heroku账号有余额、去年一键部署成功，使用了挺久的，最近想要升级一下，结果部署不上去了

rsshub提供的一键部署链接已经无法使用
https://heroku.com/deploy?template=https%3A%2F%2Fgithub.com%2FDIYgod%2FRSSHub

目前可以打开的一键部署链接是
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Felements.heroku.com%2F&template=https%3A%2F%2Fgithub.com%2FDIYgod%2FRSSHub%2Ftree%2Fmaster

但是部署失败
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment] 2024-09-26 09:56
Duplicate of #15819

**Closed** 2024-09-26 09:56 UTC
Labels: RSS bug

**Comment by mokurin000** [comment] 2024-10-01 16:31
> Duplicate of #15819

这个issue（Dangerous semver range）和15819的起因一样吗
