### ISSUE TITLE
CNKI RSS error

### ISSUE THREAD

**Issue by BensenHsu** [DIYgod/RSSHub#13610] opened 2023-10-22 14:39 UTC
### Routes

```routes
/cnki/journals/:name
```

### Full routes

```fullroutes
/cnki/journals/:name
```

### Related documentation

https://docs.rsshub.app/routes/journal#zhong-guo-zhi-wang-qi-kan

### What is expected?

A valid RSS xml content returned

### What is actually happening?

Error page for literally all journals
<img width="834" alt="image" src="https://github.com/DIYgod/RSSHub/assets/51500098/87634335-73d4-4db8-b763-ec5bdb5a6798">

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Seems like this route does not work.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2023-10-22 15:07
Duplicate of #12994

**Closed by TonyRL** 2023-10-22 15:07 UTC
Labels: RSS bug, route: v2, Count: 1/1

**Comment by BensenHsu** [comment] 2023-10-22 15:14
> Duplicate of #12994

#12994 is not resolved. The issue persists.
