### ISSUE TITLE
Facebook page route not working

### ISSUE THREAD

**Issue by clb92** [DIYgod/RSSHub#11965] opened 2023-02-27 12:29 UTC
### Routes

```routes
/facebook/page/:id
```

### Full routes

```fullroutes
/facebook/page/SuperbrugsenVamdrup
I have also tried with the numerical ID and with other Facebook pages
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#facebook

### What is expected?

I expected to get an RSS feed of the Facebook Page's posts

### What is actually happening?

I get the error message: "Error message: this route is empty, please check the original site or create an issue"

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Unraid 6.11.5; Docker version: 20.10.21; Docker image: "diygod/rsshub" (pulled today)

### Additional info

```shell
Docker container log:

info: /facebook/page/SuperbrugsenVamdrup, user IP: ::ffff:10.0.0.20
error: Error in /facebook/page/SuperbrugsenVamdrup: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>

Docker container startup command:

docker run
  -d
  --name='RSSHub'
  --net='bridge'
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Unraid"
  -e HOST_CONTAINERNAME="RSSHub"
  -e 'CACHE_TYPE'='memory'
  -e 'CACHE_EXPIRE'='5 * 60'
  -e 'REDIS_URL'='redis://localhost:6379/'
  -p '1200:1200/tcp' 'diygod/rsshub'
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by clb92** [comment] 2023-02-27 12:34
Sorry, it appears my issue may be a duplicate of: https://github.com/DIYgod/RSSHub/issues/7512 (Facebook route always "empty")

**Comment by TonyRL** [comment] 2023-02-27 13:02
Duplicate of #7512

**Closed** 2023-02-27 13:02 UTC
Labels: RSS bug, Bug Ping: Pinged, Route: v1, Count: 0/1
