### ISSUE TITLE
rsshub.app - Instagram User

### ISSUE THREAD

**Issue by jshindler** [DIYgod/RSSHub#2962] opened 2019-08-30 09:37 UTC
### Involved route
/instagram/user/:id

### What is expected?
A feed of instagram pictures. 

### What is actually happening?
```
TypeError: Cannot read property '0' of undefined
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/instagram/user.js:15:45)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:262:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:7:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)
RSSHub 发生了一些意外: 
```
I have tried it with a number of different accounts but the same result occurs.

**Comment by DIYgod** [comment] 2019-08-30 10:20
Duplicate of #2918

**Closed by DIYgod** 2019-08-30 10:20 UTC
