### ISSUE TITLE
纽约时报每日简报失效

### ISSUE THREAD

**Issue by wym3253** [DIYgod/RSSHub#7591] opened 2021-05-27 02:42 UTC
#### 路由地址（不包含参数）

```
https://rsshub.app/nytimes/morning_post
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub.app/nytimes/morning_post
```

#### 相关文档地址

- https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao-mei-ri-jian-bao

#### 预期是什么
正常获取每日简报
#### 实际发生了什么
无法输出内容
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |Debian GNU/Linux 10 (buster)  |
| Node version       |v14.17.0               |
| if Docker, version |               |

- 额外信息（日志、报错等）
官方报错：
Route requested: /nytimes/morning_post

Error message: Navigation failed because browser has disconnected!
自建报错：
Route requested: /nytimes/morning_post

Error message: Error: Failed to launch the browser process!
/home/rsshub/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/rsshub/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
    at Interface. (/home/rsshub/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)
    at Interface.emit (events.js:388:22)
    at Interface.emit (domain.js:470:12)
    at Interface.close (readline.js:429:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:388:22)
    at Socket.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by TonyRL** [comment] 2021-05-27 10:23
Duplicate of #7418

**Closed** 2022-02-18 16:01 UTC
Labels: RSS bug
