### ISSUE TITLE
没有pkg.js

### ISSUE THREAD

**Issue by PullAndRun** [DIYgod/RSSHub#14732] opened 2024-03-09 15:15 UTC
### Routes

```routes
NOROUTE
```

### Full routes

```fullroutes
NOROUTE
```

### Related documentation

NOROUTE

### What is expected?

rsshub的npm包可以使用

### What is actually happening?

![截图 2024-03-09 23-11-44](https://github.com/DIYgod/RSSHub/assets/5698974/5557efa4-b2b4-4c62-88d8-2ae0711ff9d2)

rsshub的npm包无法使用

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
有lib/pkg.ts但是没有lib/pkg.js，npm包无法调用
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2024-03-09 23:10
Duplicate of #14663

**Closed by TonyRL** 2024-03-09 23:10 UTC
Labels: RSS bug, Bug Ping: Not Found, Count: 0/1
