### ISSUE TITLE
抖音用户动态路由报错

### ISSUE THREAD

**Issue by xukecheng** [DIYgod/RSSHub#4032] opened 2020-02-19 09:05 UTC
### 路由地址
douyin/user/104255897823
### 预期是什么？
接受抖音用户动态
### 实际发生了什么？
报错
### 部署相关信息
docker-compose

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     Ubuntu          |
| Node version       |               |
| if Docker, version |       19.03.6        |

### 额外信息（日志、报错等）
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by yefoenix** [comment] 2020-02-19 09:21
duplicate of #3977

**Closed** 2020-02-19 15:10 UTC
