### ISSUE TITLE
抖音 douyin 直播间开播 路由 出错

### ISSUE THREAD

**Issue by Air433up** [DIYgod/RSSHub#13286] opened 2023-09-13 05:25 UTC
### Routes

```routes
/douyin/live/:rid
```

### Full routes

```fullroutes
https://rss-hub-kappa-lemon.vercel.app/douyin/live/675554559745
```

### Related documentation

https://docs.rsshub.app/routes/live#dou-yin-zhi-bo-zhi-bo-jian-kai-bo

### What is expected?

正常获取开播提醒的rss内容。

### What is actually happening?

![image](https://github.com/DIYgod/RSSHub/assets/60246381/965649d4-3d02-474c-b8ee-826013271973)

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

https://vercel.com/

### Additional info

```shell
使用演示demo是正常获取的，但自建就出错了，想请教一下大佬是啥问题呢？
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2023-09-13 05:51
https://github.com/DIYgod/RSSHub/discussions/11047#discussioncomment-3836950

**Comment by TonyRL** [comment] 2023-09-13 05:52
Duplicate of #11047

**Closed by TonyRL** 2023-09-13 05:52 UTC
Labels: RSS bug, Bug Ping: Pinged, Route: v2, Count: 1/1
