### ISSUE TITLE
kemono.party: New interface breaks RSSHub

### ISSUE THREAD

**Issue by guldor12** [DIYgod/RSSHub#11112] opened 2022-10-18 14:05 UTC
### Routes

```routes
/kemono
```

### Full routes

```fullroutes
/kemono/fanbox/3489777
```

### Related documentation

https://docs.rsshub.app/en/anime.html#kemono

### What is expected?

RSSHub serves feeds for Kemono users.

### What is actually happening?

RSSHub returns a 404 error.

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Debian 11.5, Node: v16.17.0, Docker: 20.10.5+dfsg1, Git Hash: 7ef81ae

### Additional info

```shell
Kemono completely changed their interface recently and they will probably do the same for Coomer soon.
```

### This is not a duplicated issue

- [x] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by purple512** [comment] 2022-10-18 14:29
I think the bot closed this in error. It is a real issue that was caused by a site redesign, and it's still broken. I don't know why that results in a 404.

**Closed** 2022-10-23 05:37 UTC
Labels: RSS bug, Bug Ping: Not Found, Count: 0/1
