### ISSUE TITLE
Unable to access picuki route, returns "Protocol error (Runtime.callFunctionOn): Target closed."

### ISSUE THREAD

**Issue by patrick330602** [DIYgod/RSSHub#11673] opened 2023-01-23 11:13 UTC
### Routes

```routes
/picuki/profile/:id/:functionalFlag?
```

### Full routes

```fullroutes
/picuki/profile/oto_hamster
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#picuki-user-profile

### What is expected?

It should return a rss of instagram account content.

### What is actually happening?

It returns an error message: 

> Waiting for selector `.wrapper` failed: Protocol error (Runtime.callFunctionOn): Target closed.

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

OS: Linux, Node version: v16.19.0, Docker: 20.10.23

### Additional info

```shell
Route requested: /profile/oto_hamster

Error message: Waiting for selector `.wrapper` failed: Protocol error (Runtime.callFunctionOn): Target closed.

Helpful Information to provide when opening issue:
Path: /profile/oto_hamster/1
Node version: v16.19.0
Git Hash: 131374c
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2023-01-23 12:07
/test
```routes
/picuki/profile/oto_hamster
```

**Comment by TonyRL** [comment] 2023-01-23 12:10
Duplicate of #11661

**Closed by TonyRL** 2023-01-23 12:10 UTC
Labels: Bug Ping: Pinged, Route: v2, anti-crawler, Count: 1/1

**Comment by patrick330602** [comment] 2023-01-23 15:15
@TonyRL Double checked with that that, not the same error message. I used the latest version of RSSHub image.

**Comment by TonyRL** [comment] 2023-01-23 15:21
> Requests from public demo might be filtered by WAF. Deploy yours plz.

_Originally posted by Rongronggg9 in https://github.com/DIYgod/RSSHub/issues/11661#issuecomment-1398629646_

**Comment by TonyRL** [comment] 2023-01-23 17:12
FYI, it works in my self-hosted instance 

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11386903/214102460-c2f4d7f9-91a2-449b-bca9-8b0a26ec5370.png)

</details>

You can try setting `DEFAULT_STEALTH` to `true` for browserless.

If your server does not have sufficient free memory(>2GiB) for chrome, you may need to extend browserless' `CONNECTION_TIMEOUT` and RSSHub's `REQUEST_TIMEOUT` as well
