### ISSUE TITLE
请求添加知识星球

### ISSUE THREAD

**Issue by yyrbzrrs** [DIYgod/RSSHub#17884] opened 2024-12-13 12:36 UTC
### Category

BBS

### Website URL

https://www.zsxq.com/group/

### Website description

知识付费社群工具

### What content should be included?

- 用户名
- 发布日期
- 正文内容

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment] 2024-12-13 23:16
Duplicate of #5751

**Closed by TonyRL** 2024-12-13 23:16 UTC
Labels: RSS proposal, RSS created
