### ISSUE TITLE
Picuki:Error message: Could not find Chromium (rev. 1083080).

### ISSUE THREAD

**Issue by lee199111** [DIYgod/RSSHub#11846] opened 2023-02-12 12:52 UTC
### Routes

```routes
/picuki/profile/:id/:functionalFlag?
```

### Full routes

```fullroutes
/picuki/profile/windancer0809
```

### Related documentation

https://docs.rsshub.app/social-media.html#picuki-yong-hu

### What is expected?

rss 地址能访问

### What is actually happening?

Looks like something went wrong
Route requested: /profile/windancer0809
Error message: Could not find Chromium (rev. 1083080). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /profile/windancer0809
Node version: v18.12.1
Git Hash: 56e2948
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行[汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)

### Deployment information

Self-hosted

### Additional info

```shell
Route requested: /profile/windancer0809
Error message: Could not find Chromium (rev. 1083080). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /profile/windancer0809
Node version: v18.12.1
Git Hash: 56e2948
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2023-02-12 13:34
Duplicate of #11046

**Closed by TonyRL** 2023-02-12 13:34 UTC
Labels: RSS bug, Bug Ping: Pinged, Route: v2, Count: 1/1
