### ISSUE TITLE
INSTAGRAM : Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by imTHAI** [DIYgod/RSSHub#15940] opened 2024-06-19 07:48 UTC
### Routes

```routes
/instagram/2/:category/:key
```

### Full routes

```fullroutes
/instagram/2/user/laboiteacuriosites
/instagram/2/user/todayyearsold

etc..
```

### Related documentation

https://docs.rsshub.app/routes/social-media#instagram

### What is expected?

xml page

### What is actually happening?

Error Message:
TypeError: Cannot read properties of undefined (reading 'includes')
Route: /instagram/2/:category/:key
Full Route: /instagram/2/user/dailycollegecontent
Node Version: v22.3.0
Git Hash: 54d0ee98
Git Date: Tue, 18 Jun 2024 20:41:37 GMT

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

RSSHub docker container on my home server (unraid).

### Additional info

```shell
It’s been going on for several weeks, and for all my instagram subscriptions (+40).

```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2024-06-19 13:19
Duplicate of #15061

**Closed by TonyRL** 2024-06-19 13:19 UTC
Labels: RSS bug
