### ISSUE TITLE
Facebook page RSS is not working

### ISSUE THREAD

**Issue by salieri-as** [DIYgod/RSSHub#4485] opened 2020-04-18 10:27 UTC
### Involved route
Facebook RSS route

### What is expected? 
Facebook page RSS feed

### What is actually happening? 
it's not working, i've tested several other facebook page and all of them are giving me an error page. Only the provided page example in https://docs.rsshub.app/social-media.html#facebook that works.

### Additional info (logs errors etc)
![error log](https://user-images.githubusercontent.com/36794203/79635194-bbdca380-8199-11ea-92ad-4b2e7783e311.png)

Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

**Comment by DIYgod** [comment] 2020-04-19 11:28
Duplicate of #3921

**Closed by DIYgod** 2020-04-19 11:28 UTC
