### ISSUE TITLE
Twitter User RSS Sub went wrong

### ISSUE THREAD

**Issue by Summerlve** [DIYgod/RSSHub#8865] opened 2022-01-12 01:37 UTC
### Routes

https://rsshub.app/twitter/user/Kojima_Hideo

### Full routes

https://rsshub.app/twitter/user/Kojima_Hideo

### Related documentation

https://docs.rsshub.app/social-media.html#twitter

### What is expected?

follow twitter user by rsshub。

### What is actually happening?

https://rsshub.app/twitter/user/Kojima_Hideo
this url returned a error.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
https://rsshub.app/twitter/user/Kojima_Hideo returns error.
but when add a readable=1 suffix, such as: https://rsshub.app/twitter/user/Kojima_Hideo/readable=1, it works
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Fatpandac** [comment] 2022-01-12 03:12
可能反爬了，在我自建的 [rss](https://rss.fatpandac.tk/twitter/user/Kojima_Hideo) 是可以的

**Comment by Summerlve** [comment] 2022-01-12 04:10
But when I add readable=1 flag, its works. So I think it's not about anti-spider policy.

**Comment by TonyRL** [comment] 2022-01-12 12:13
`/twitter/user/Kojima_Hideo` works at the time of replying.

Possible duplicate of #8650

![image](https://user-images.githubusercontent.com/11386903/149137774-b6242599-43a2-44dc-b19b-b8d8a5911e8d.png)

**Comment by Summerlve** [comment] 2022-01-14 00:32
Yeap, same issue with [#8650](https://github.com/DIYgod/RSSHub/issues/8650), Maybe some configurations for RSSHub was updated, but RSSHub Radar do not.

**Closed** 2022-04-05 21:11 UTC
Labels: RSS bug
