### ISSUE TITLE
Support for Reddit

### ISSUE THREAD

**Issue by 0xRaduan** [DIYgod/RSSHub#14376] opened 2024-02-02 13:48 UTC
### Category

Social Media

### Website URL

https://reddit.com

### Website description

Would be great to have reddit, so I can read posts from a particular sub-reddit via RSS.

### What content should be included?

For now just main post(text for MVP), and also in the future versions would be great to retrieve comments as well(either as a separate API path, or somehow differently)

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment] 2024-02-02 14:57
Duplicate of #359

**Closed by TonyRL** 2024-02-02 14:57 UTC
Labels: RSS proposal
