### ISSUE TITLE
Strange path in package @/xx, therefore import error when start

### ISSUE THREAD

**Issue by alTach** [DIYgod/RSSHub#15565] opened 2024-05-12 11:35 UTC
### Routes

```routes
NOROUTE
```

### Full routes

```fullroutes
NOROUTE
```

### Related documentation

https://docs.rsshub.app/guide/

### What is expected?

Expected that app is started without error.

### What is actually happening?

`
[2:19:08 PM] Starting compilation in watch mode...

node_modules/rsshub/lib/pkg.ts:1:27 - error TS2307: Cannot find module '@/config' or its corresponding type declarations.

1 import { setConfig } from '@/config';
                            ~~~~~~~~~~

node_modules/rsshub/lib/pkg.ts:15:25 - error TS2307: Cannot find module '@/app' or its corresponding type declarations.

15     app = (await import('@/app')).default;
                           ~~~~~~~

src/app.service.ts:6:8 - error TS1192: Module '"/rss_tes_tapp/node_modules/rsshub/lib/pkg"' has no default export.

6 import RSSHub from 'rsshub';
         ~~~~~~

[2:19:22 PM] Found 3 errors. Watching for file changes.

`

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

_No response_

### Additional info


"rsshub": "^1.0.0-master.5e8ea80"

I just installed the package and took the code from the example and I get such errors. The library uses a strange path. I believe, the better way for fix issue is update path in library.



### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment] 2024-05-12 12:27
Duplicate of #14930

**Closed by TonyRL** 2024-05-12 12:27 UTC
Labels: RSS bug
