### ISSUE TITLE
某个抖音博主的视频更新

### ISSUE THREAD

**Issue by jiucai-i** [DIYgod/RSSHub#17418] opened 2024-11-02 08:52 UTC
### Category

Social Media

### Website URL

https://www.douyin.com

### Website description

有些视频博主在B站没有账号，但是视频是有些用处的

### What content should be included?

某个抖音博主ID更新的视频

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment] 2024-11-02 11:15
Duplicate of #12029

**Closed by TonyRL** 2024-11-02 11:15 UTC
Labels: RSS proposal
